- name: Configure network device
  hosts: all
  connection: local
  gather_facts: False
  vars:
    netconf:
      host: "{{ inventory_hostname }}"
      timeout: 30
      port: 22

  tasks:

    - name: configure hostname
      junos_config:
        lines:
          - set system host-name "{{ inventory_hostname }}"
        #replace: yes
        provider: "{{ netconf }}"
