---
 - name: Make sure file dir exists
   file:
     path: "{{ role_path }}/files"
     state: directory

 - name: Make sure log dir exists
   file:
     path: "{{ role_path }}/files/log"
     state: directory

 - name: Building configuration from jinja2 template
   template:
     src: "{{ role_path }}/templates/default.set.j2"
     dest: "{{ role_path }}/files/{{ inventory_hostname }}.set"

 - name: Configure hostname
   junos_config:
     vars:
       netconf:
         host: "{{ inventory_hostname }}"
         timeout: 60
         port: 22
     src: "{{ role_path }}/files/{{ inventory_hostname }}.set"
     src_format:  set
     #replace: yes
     provider: "{{ netconf }}"
