---
- hosts: all
  gather_facts: true

  tasks:
  - name: "What's vCenter server user name?"
    debug:
       msg: '{{ vmuser }}'

  - name: "What's vCenter server password?"
    debug:
       msg: '{{ vmpassword }}'
       