- name: Power on all vMX VMs
  hosts: all
  connection: local

  tasks:
    - name: Set the state of a virtual machine to powered-on
      vmware_guest_powerstate:
        hostname: "{{ vcenter }}"
        username: "{{ vmuser }}"
        password: "{{ vmpassword }}"
        validate_certs: no
        folder: "{{ vmdc }}"
        name: "{{ vmname }}"
        state: powered-on
      register: deploy