- name: Power on all vMX VMs
  hosts: all
  connection: local

  tasks:
    - name: configure prefix list
      vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter }}"
        username: "{{ vmuser }}"
        password: "{{ vmpassword }}"
        name: "{{ vmname }}"
        state: poweredon
        datacenter: "{{ vmdc }}"
        esxi_hostname: "{{ vmwarehost }}"
