- name: Power off all vMX VMs
  hosts: all
  serial: 1
  connection: local

  tasks:
    - name: Set the state of a virtual machine to powered-off
      vmware_guest_powerstate:
        hostname: "{{ vcenter }}"
        username: "{{ vmuser }}"
        password: "{{ vmpassword }}"
        validate_certs: no
        folder: "{{ vmdc }}"
        name: "{{ vmname }}"
        state: suspended
      register: deploy